"""
PDF Generator - Converts markdown documentation to PDF.

Uses fpdf2 for pure Python PDF generation without native dependencies.
Includes Mermaid diagram rendering to PNG via mermaid-cli.
"""

import logging
import re
import tempfile
import os
from io import BytesIO
from typing import Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)


class PDFGenerator:
    """Generates PDF documents from markdown documentation."""

    def __init__(self, render_mermaid: bool = True):
        """
        Initialize PDF generator.

        Args:
            render_mermaid: Whether to render Mermaid diagrams to PNG (requires mmdc)
        """
        self.render_mermaid = render_mermaid
        self._mermaid_renderer = None
        self._temp_files: List[str] = []

    def _get_mermaid_renderer(self):
        """Lazy load mermaid renderer."""
        if self._mermaid_renderer is None:
            try:
                from .mermaid_renderer import get_mermaid_renderer
                self._mermaid_renderer = get_mermaid_renderer()
            except ImportError:
                logger.warning("Mermaid renderer not available")
                self._mermaid_renderer = None
        return self._mermaid_renderer

    def _cleanup_temp_files(self):
        """Clean up temporary files."""
        for path in self._temp_files:
            try:
                if os.path.exists(path):
                    os.unlink(path)
            except Exception:
                pass
        self._temp_files = []

    def generate_pdf(self, markdown_content: str, service_name: str = "Documentation") -> bytes:
        """
        Generate PDF from markdown content.

        Args:
            markdown_content: Markdown documentation string
            service_name: Service name for the document title

        Returns:
            PDF bytes
        """
        try:
            from fpdf import FPDF

            # Create PDF
            pdf = FPDF()
            pdf.set_auto_page_break(auto=True, margin=15)

            # Add cover page
            pdf.add_page()
            pdf.set_font('Helvetica', 'B', 36)
            pdf.ln(80)
            pdf.cell(0, 20, service_name, ln=True, align='C')
            pdf.set_font('Helvetica', '', 16)
            pdf.ln(10)
            pdf.cell(0, 10, 'Technical Documentation', ln=True, align='C')
            pdf.ln(5)
            pdf.set_font('Helvetica', 'I', 12)
            pdf.cell(0, 10, 'Auto-generated by FlowRAG', ln=True, align='C')
            pdf.ln(60)
            pdf.set_font('Helvetica', '', 10)
            pdf.cell(0, 10, f'Generated on {datetime.now().strftime("%B %d, %Y at %I:%M %p")}', ln=True, align='C')

            # Add content pages
            pdf.add_page()
            self._render_markdown(pdf, markdown_content)

            # Get PDF bytes
            pdf_bytes = pdf.output()
            logger.info(f"Generated PDF for {service_name}: {len(pdf_bytes)} bytes")

            # Cleanup temp files
            self._cleanup_temp_files()

            return pdf_bytes

        except ImportError as e:
            logger.error(f"fpdf2 not installed: {e}")
            raise RuntimeError(
                "PDF generation requires fpdf2. "
                "Install with: pip install fpdf2"
            )
        except Exception as e:
            logger.error(f"PDF generation failed: {e}", exc_info=True)
            self._cleanup_temp_files()
            raise RuntimeError(f"PDF generation failed: {str(e)}")

    def _render_markdown(self, pdf, markdown_content: str):
        """Render markdown content to PDF."""
        lines = markdown_content.split('\n')
        in_code_block = False
        code_block_content = []
        code_block_lang = ""
        in_table = False
        table_rows = []

        i = 0
        while i < len(lines):
            line = lines[i]

            # Handle code blocks
            if line.startswith('```'):
                # Flush any pending table
                if in_table and table_rows:
                    self._render_table(pdf, table_rows)
                    table_rows = []
                    in_table = False

                if in_code_block:
                    # End code block
                    in_code_block = False
                    self._render_code_block(pdf, '\n'.join(code_block_content), code_block_lang)
                    code_block_content = []
                    code_block_lang = ""
                else:
                    # Start code block
                    in_code_block = True
                    code_block_lang = line[3:].strip()
                i += 1
                continue

            if in_code_block:
                code_block_content.append(line)
                i += 1
                continue

            # Handle tables (lines starting with |)
            if line.strip().startswith('|') and line.strip().endswith('|'):
                # Check if it's a separator line (|---|---|)
                if re.match(r'^\|[\s\-:|]+\|$', line.strip()):
                    # Skip separator line
                    i += 1
                    continue

                # Parse table row
                cells = [cell.strip() for cell in line.strip().split('|')[1:-1]]
                if cells:
                    table_rows.append(cells)
                    in_table = True
                i += 1
                continue

            # If we were in a table and hit a non-table line, render the table
            if in_table and table_rows:
                self._render_table(pdf, table_rows)
                table_rows = []
                in_table = False

            # Skip empty lines
            if not line.strip():
                pdf.ln(3)
                i += 1
                continue

            # Handle headers
            if line.startswith('# '):
                self._render_h1(pdf, line[2:].strip())
            elif line.startswith('## '):
                self._render_h2(pdf, line[3:].strip())
            elif line.startswith('### '):
                self._render_h3(pdf, line[4:].strip())
            elif line.startswith('#### '):
                self._render_h4(pdf, line[5:].strip())
            elif line.startswith('- ') or line.startswith('* '):
                self._render_list_item(pdf, line[2:].strip())
            elif line.startswith('---'):
                self._render_horizontal_rule(pdf)
            elif line.startswith('**') and line.endswith('**'):
                # Bold text line
                self._render_bold_line(pdf, line[2:-2])
            else:
                self._render_paragraph(pdf, line)

            i += 1

        # Flush any remaining table
        if in_table and table_rows:
            self._render_table(pdf, table_rows)

    def _render_h1(self, pdf, text: str):
        """Render H1 header."""
        pdf.ln(10)
        pdf.set_font('Helvetica', 'B', 24)
        pdf.set_text_color(26, 26, 46)  # Dark blue
        # Handle multi-cell for long text
        pdf.multi_cell(0, 12, self._clean_text(text))
        # Add underline
        pdf.set_draw_color(74, 144, 217)  # Blue
        pdf.set_line_width(1)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        pdf.set_text_color(0, 0, 0)

    def _render_h2(self, pdf, text: str):
        """Render H2 header."""
        pdf.ln(8)
        pdf.set_font('Helvetica', 'B', 18)
        pdf.set_text_color(45, 55, 72)
        pdf.multi_cell(0, 10, self._clean_text(text))
        # Add light underline
        pdf.set_draw_color(226, 232, 240)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_text_color(0, 0, 0)

    def _render_h3(self, pdf, text: str):
        """Render H3 header."""
        pdf.ln(6)
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(74, 85, 104)
        pdf.multi_cell(0, 8, self._clean_text(text))
        pdf.ln(2)
        pdf.set_text_color(0, 0, 0)

    def _render_h4(self, pdf, text: str):
        """Render H4 header."""
        pdf.ln(4)
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(113, 128, 150)
        pdf.multi_cell(0, 7, self._clean_text(text))
        pdf.ln(2)
        pdf.set_text_color(0, 0, 0)

    def _render_paragraph(self, pdf, text: str):
        """Render paragraph text."""
        pdf.set_font('Helvetica', '', 11)
        pdf.set_text_color(51, 51, 51)
        # Clean markdown formatting
        cleaned = self._clean_text(text)
        pdf.multi_cell(0, 6, cleaned)
        pdf.set_text_color(0, 0, 0)

    def _render_bold_line(self, pdf, text: str):
        """Render bold text line."""
        pdf.set_font('Helvetica', 'B', 11)
        pdf.multi_cell(0, 6, self._clean_text(text))
        pdf.set_font('Helvetica', '', 11)

    def _render_list_item(self, pdf, text: str):
        """Render list item."""
        pdf.set_font('Helvetica', '', 11)
        pdf.set_x(20)  # Indent
        pdf.multi_cell(0, 6, f"- {self._clean_text(text)}")

    def _render_horizontal_rule(self, pdf):
        """Render horizontal rule."""
        pdf.ln(5)
        pdf.set_draw_color(200, 200, 200)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

    def _render_table(self, pdf, rows: List[List[str]]):
        """Render a table with proper column sizing."""
        if not rows:
            return

        pdf.ln(3)

        # Calculate column widths based on content
        num_cols = len(rows[0])
        page_width = 190  # usable width (210 - 20 margins)

        # Find max content length per column
        col_max_lens = [0] * num_cols
        for row in rows:
            for i, cell in enumerate(row[:num_cols]):
                cleaned = self._clean_text(cell)
                col_max_lens[i] = max(col_max_lens[i], len(cleaned))

        # Calculate proportional widths (min 20mm per column)
        total_len = sum(col_max_lens) or 1
        col_widths = []
        min_width = 20
        for length in col_max_lens:
            width = max(min_width, (length / total_len) * page_width)
            col_widths.append(width)

        # Scale down if total exceeds page width
        total_width = sum(col_widths)
        if total_width > page_width:
            scale = page_width / total_width
            col_widths = [w * scale for w in col_widths]

        # Render header row (first row)
        pdf.set_fill_color(74, 144, 217)  # Blue header
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 9)

        row_height = 7
        x_start = 10

        if rows:
            header = rows[0]
            pdf.set_x(x_start)
            for i, cell in enumerate(header[:num_cols]):
                width = col_widths[i] if i < len(col_widths) else 30
                cleaned = self._clean_text(cell)
                # Truncate if too long
                if len(cleaned) > int(width / 2):
                    cleaned = cleaned[:int(width / 2) - 2] + ".."
                pdf.cell(width, row_height, cleaned, border=1, fill=True)
            pdf.ln(row_height)

        # Render data rows
        pdf.set_fill_color(245, 245, 245)  # Light gray alternating
        pdf.set_text_color(51, 51, 51)
        pdf.set_font('Helvetica', '', 9)

        for row_idx, row in enumerate(rows[1:], start=1):
            fill = row_idx % 2 == 0
            pdf.set_x(x_start)

            for i, cell in enumerate(row[:num_cols]):
                width = col_widths[i] if i < len(col_widths) else 30
                cleaned = self._clean_text(cell)
                # Truncate if too long
                if len(cleaned) > int(width / 2):
                    cleaned = cleaned[:int(width / 2) - 2] + ".."
                pdf.cell(width, row_height, cleaned, border=1, fill=fill)
            pdf.ln(row_height)

        pdf.ln(3)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 11)

    def _render_code_block(self, pdf, code: str, lang: str = ""):
        """Render code block with background."""
        pdf.ln(3)

        # Check if it's a mermaid diagram
        if lang.lower() == 'mermaid':
            self._render_mermaid_diagram(pdf, code)
            return

        # Set background color for code block
        pdf.set_fill_color(30, 30, 30)  # Dark background
        pdf.set_text_color(212, 212, 212)  # Light text
        pdf.set_font('Courier', '', 9)

        # Calculate height needed
        lines = code.split('\n')
        y_start = pdf.get_y()

        # Limit code block size
        max_lines = 30
        if len(lines) > max_lines:
            lines = lines[:max_lines]
            lines.append(f"... ({len(code.split(chr(10))) - max_lines} more lines)")

        # Draw background rectangle
        line_height = 5
        block_height = len(lines) * line_height + 10
        pdf.rect(10, y_start, 190, block_height, 'F')

        # Add code text
        pdf.set_xy(15, y_start + 5)
        for line in lines:
            # Truncate long lines
            if len(line) > 90:
                line = line[:87] + "..."
            pdf.cell(0, line_height, line)
            pdf.ln(line_height)
            pdf.set_x(15)

        pdf.ln(5)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 11)

    def _render_mermaid_diagram(self, pdf, code: str):
        """Render Mermaid diagram as PNG image or placeholder."""
        # Determine diagram type for title
        first_line = code.split('\n')[0].strip().lower()
        if 'graph' in first_line or 'flowchart' in first_line:
            diagram_type = "Flowchart"
        elif 'sequence' in first_line:
            diagram_type = "Sequence Diagram"
        elif 'class' in first_line:
            diagram_type = "Class Diagram"
        elif 'er' in first_line:
            diagram_type = "Entity Relationship Diagram"
        else:
            diagram_type = "Diagram"

        # Try to render as PNG if mermaid rendering is enabled
        if self.render_mermaid:
            renderer = self._get_mermaid_renderer()
            if renderer and renderer.available:
                try:
                    # Get appropriate dimensions
                    width, height = renderer.get_diagram_dimensions(code)

                    # Render to PNG
                    png_bytes = renderer.render_to_png(code, width, height)

                    if png_bytes:
                        # Save to temp file (fpdf requires file path)
                        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as f:
                            f.write(png_bytes)
                            temp_path = f.name

                        self._temp_files.append(temp_path)

                        # Add diagram title
                        pdf.ln(3)
                        pdf.set_font('Helvetica', 'B', 11)
                        pdf.set_text_color(74, 85, 104)
                        pdf.cell(0, 8, f"{diagram_type}", ln=True)
                        pdf.set_text_color(0, 0, 0)

                        # Calculate image dimensions to fit page
                        # Page width is 210mm, margins are 10mm each side = 190mm usable
                        # Convert pixel dimensions to mm (assuming 96 DPI)
                        max_width_mm = 180  # Leave some margin
                        max_height_mm = 180  # Max height before page break

                        img_width_mm = width * 0.264583  # pixels to mm
                        img_height_mm = height * 0.264583

                        # Scale to fit
                        scale = min(max_width_mm / img_width_mm, max_height_mm / img_height_mm, 1.0)
                        final_width = img_width_mm * scale
                        final_height = img_height_mm * scale

                        # Check if we need a new page
                        if pdf.get_y() + final_height > 270:
                            pdf.add_page()

                        # Center the image
                        x_offset = (210 - final_width) / 2

                        # Add the image
                        pdf.image(temp_path, x=x_offset, w=final_width, h=final_height)
                        pdf.ln(5)

                        logger.info(f"Rendered Mermaid {diagram_type} as PNG image")
                        return

                except Exception as e:
                    logger.warning(f"Failed to render Mermaid diagram: {e}")
                    # Fall through to placeholder

        # Fallback to placeholder
        self._render_mermaid_placeholder(pdf, code, diagram_type)

    def _render_mermaid_placeholder(self, pdf, code: str, diagram_type: str = "Diagram"):
        """Render a placeholder for mermaid diagrams when PNG rendering is not available."""
        # Draw gradient-like box
        y_start = pdf.get_y()
        pdf.set_fill_color(102, 126, 234)  # Purple/blue
        pdf.rect(10, y_start, 190, 60, 'F')

        # Add title
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_xy(15, y_start + 10)
        pdf.cell(0, 8, f"[Diagram] {diagram_type}")

        # Add note
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_xy(15, y_start + 22)
        pdf.cell(0, 6, "View interactive diagram in web interface")

        # Add small code preview
        pdf.set_font('Courier', '', 8)
        pdf.set_xy(15, y_start + 35)
        preview = code[:100] + "..." if len(code) > 100 else code
        preview = preview.replace('\n', ' ')
        pdf.multi_cell(180, 4, preview)

        pdf.set_y(y_start + 65)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Helvetica', '', 11)

    def _clean_text(self, text: str) -> str:
        """Clean markdown formatting from text."""
        # Remove inline code backticks
        text = re.sub(r'`([^`]+)`', r'\1', text)
        # Remove bold/italic markers
        text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
        text = re.sub(r'\*([^*]+)\*', r'\1', text)
        text = re.sub(r'__([^_]+)__', r'\1', text)
        text = re.sub(r'_([^_]+)_', r'\1', text)
        # Remove links, keep text
        text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
        # Handle special characters that might cause issues
        text = text.replace('→', '->')
        text = text.replace('←', '<-')
        text = text.replace('•', '-')
        # Encode to latin-1 compatible (fpdf default)
        text = text.encode('latin-1', errors='replace').decode('latin-1')
        return text

    def generate_pdf_stream(self, markdown_content: str, service_name: str = "Documentation") -> BytesIO:
        """
        Generate PDF and return as BytesIO stream.

        Args:
            markdown_content: Markdown documentation string
            service_name: Service name for the document title

        Returns:
            BytesIO stream containing PDF
        """
        pdf_bytes = self.generate_pdf(markdown_content, service_name)
        return BytesIO(pdf_bytes)


# Singleton instance
_pdf_generator: Optional[PDFGenerator] = None


def get_pdf_generator() -> PDFGenerator:
    """Get or create PDF generator instance."""
    global _pdf_generator

    if _pdf_generator is None:
        _pdf_generator = PDFGenerator(render_mermaid=True)

    return _pdf_generator
